interface MyObject {
  [key: string]: any;
}

const obj: MyObject = {
  gaza2: require("@/assets/images/mapImages/gaza2.jpg"),
  goosegreen: require("@/assets/images/mapImages/goosegreen.jpg"),
  sbenehoutskirts: require("@/assets/images/mapImages/sbenehoutskirts.jpg"),
  muttrahcity2: require("@/assets/images/mapImages/muttrahcity2.jpg"),
  kashandesert: require("@/assets/images/mapImages/kashandesert.jpg"),
  masirah: require("@/assets/images/mapImages/masirah.jpg"),
  route: require("@/assets/images/mapImages/route.jpg"),
  albasrah2: require("@/assets/images/mapImages/albasrah2.jpg"),
  bamyan: require("@/assets/images/mapImages/bamyan.jpg"),
  blackgold: require("@/assets/images/mapImages/blackgold.jpg"),
  stalingradsummer: require("@/assets/images/mapImages/stalingradsummer.jpg"),
  beirut: require("@/assets/images/mapImages/beirut.jpg"),
  fallujahwest: require("@/assets/images/mapImages/fallujahwest.jpg"),
  shijiavalley: require("@/assets/images/mapImages/shijiavalley.jpg"),
  roadtodamascus: require("@/assets/images/mapImages/roadtodamascus.jpg"),
  zakho: require("@/assets/images/mapImages/zakho.jpg"),
  musaqala: require("@/assets/images/mapImages/musaqala.jpg"),
  raselmasri2: require("@/assets/images/mapImages/raselmasri2.jpg"),
  khamisiyah: require("@/assets/images/mapImages/khamisiyah.jpg"),
  operationmarlin: require("@/assets/images/mapImages/operationmarlin.jpg"),
  adak: require("@/assets/images/mapImages/adak.jpg"),
  opbarracuda: require("@/assets/images/mapImages/opbarracuda.jpg"),
  ramiel: require("@/assets/images/mapImages/ramiel.jpg"),
  shahadah: require("@/assets/images/mapImages/shahadah.jpg"),

  ulyanovsk: require("@/assets/images/mapImages/ulyanovsk.jpg"),
  assaultongrozny: require("@/assets/images/mapImages/assaultongrozny.jpg"),
  silenteagle: require("@/assets/images/mapImages/silenteagle.jpg"),
  kafarhalab: require("@/assets/images/mapImages/kafarhalab.jpg"),
  stalingrad: require("@/assets/images/mapImages/stalingrad.jpg"),
  pavlovskbay: require("@/assets/images/mapImages/pavlovskbay.jpg"),
  kokan: require("@/assets/images/mapImages/kokan.jpg"),
  hadespeak: require("@/assets/images/mapImages/hadespeak.jpg"),
  asadkhal: require("@/assets/images/mapImages/asadkhal.jpg"),
  karbala: require("@/assets/images/mapImages/karbala.jpg"),
  operationbobcat: require("@/assets/images/mapImages/operationbobcat.jpg"),
  burningsands: require("@/assets/images/mapImages/burningsands.jpg"),
  lashkarvalley: require("@/assets/images/mapImages/lashkarvalley.jpg"),
  ironridge: require("@/assets/images/mapImages/ironridge.jpg"),
  vadsocity: require("@/assets/images/mapImages/vadsocity.jpg"),
  operationbrunswick: require("@/assets/images/mapImages/operationbrunswick.jpg"),
  vungro: require("@/assets/images/mapImages/vungro.jpg"),
  grostok: require("@/assets/images/mapImages/grostok.jpg"),
  tadsae: require("@/assets/images/mapImages/tadsae.jpg"),
  kunarprovince: require("@/assets/images/mapImages/kunarprovince.jpg"),
  carentan: require("@/assets/images/mapImages/carentan.jpg"),
  battleofiadrang: require("@/assets/images/mapImages/battleofiadrang.jpg"),
  yamalia: require("@/assets/images/mapImages/yamalia.jpg"),
  korengal: require("@/assets/images/mapImages/korengal.jpg"),
  operationsoulrebel: require("@/assets/images/mapImages/operationsoulrebel.jpg"),
  nuijamaa: require("@/assets/images/mapImages/nuijamaa.jpg"),
  fieldsofkassel: require("@/assets/images/mapImages/fieldsofkassel.jpg"),
  merville: require("@/assets/images/mapImages/merville.jpg"),
  operationthunder: require("@/assets/images/mapImages/operationthunder.jpg"),
  wandashan: require("@/assets/images/mapImages/wandashan.jpg"),
};

export default obj;
